name: Hugo-CI
on:
  push:
    branches: [ develop ]
    paths:
      - 'Docs/**'

jobs:
  job-one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: build Hugo public site
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY }}
        port: ${{ secrets.SSHPORT }}
        script: |
          git clone --single-branch --branch develop https://github.com/aspose-html/Aspose.HTML-for-.NET.git || (cd Aspose.HTML-for-.NET; git pull)
          cp -R Aspose.HTML-for-.NET/Docs/NET/* aspose-prototype/content/net
          cd aspose-prototype
          hugo --baseURL https://docs.aspose.com/html
          sudo cp -R aspose-prototype/public/net/* ../net-23