name: Hugo-CI
on:
  push:
    branches: [ develop ]

jobs:
  job-one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: build Hugo public site
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY }}
        port: ${{ secrets.SSHPORT }}
        script: |
          ls -l
          cd workspace
          ls -l
          pwd