name: Hugo-CI
on:
  push:
    branches: [ develop ]

jobs:
  job-one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: FranzDiebold/github-env-vars-action@v1.2.0
    - name: Print environment variables
      env:
        REPOSITORY_NAME: $GITHUB_REPOSITORY_NAME
    - name: build Hugo public site
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY }}
        port: ${{ secrets.SSHPORT }}
        script: |
          git clone ${{ github.repository }}
          cd ${{ REPOSITORY_NAME }}