name: Hugo-CI
on:
  push:
    branches: [ develop ]

jobs:
  job-one:
    - run: echo ::set-env name=REPOSITORY_NAME::$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//")
      shell: bash
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: build Hugo public site
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY }}
        port: ${{ secrets.SSHPORT }}
        script: |
          git clone ${{ github.repository }}
          cd ${{ REPOSITORY_NAME }}